theme: jekyll-theme-cayman
author: sibyx
title: phpGPX library
description: Simple library for reading and creating GPX files written in PHP.
gems:
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-sitemap
social:
  name: Jakub Dubec
  links:
    - https://www.facebook.com/dubecj
    - https://github.com/Sibyx
    - https://keybase.io/jakubdubec

jekyll_analytics:
  GoogleAnalytics:
    id: UA-99333937-1
    anonymizeIp: false