<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
namespace mvbplugins\fotoramamulti;

$path = plugin_dir_path(__FILE__);
require_once $path . 'custom_mine_types.php'; 


class FotoramaElevation {
	private $fotorama_elevation_options;
	private $up_dir = '';    
	private $min_height_map = 100;
	private $max_height_map = 1000;
	private $min_height_chart = 100;
	private $max_height_chart = 800;
	private $min_width = 100;
	private $max_width = 1500;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'fotorama_elevation_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'fotorama_elevation_page_init' ) );
	}

	public function fotorama_elevation_add_plugin_page() {
		add_options_page(
			'Fotorama-Elevation', // page_title
			'Fotorama-Elevation', // menu_title
			'manage_options', // capability
			'fotorama-elevation', // menu_slug
			array( $this, 'fotorama_elevation_create_admin_page' ) // function
		);
	}

	public function fotorama_elevation_create_admin_page() {
		$this->fotorama_elevation_options = get_option( 'fotorama_elevation_option_name' );
		$this->up_dir = wp_get_upload_dir()['basedir'];     // upload_dir

		$path_to_images_for_fotorama = $this->fotorama_elevation_options['path_to_images_for_fotorama_0']; // Path to Images for Fotorama
		$colour_theme_for_leaflet_elevation = $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1']; // Colour Theme for Leaflet Elevation
		$path_to_gpx_files = $this->fotorama_elevation_options['path_to_gpx_files_2']; // Path to GPX-Files
		$download_gpx_files = $this->fotorama_elevation_options['download_gpx_files_3']; // Download GPX-Files
		$show_caption = $this->fotorama_elevation_options['show_caption_4']; // Show Caption
		$images_with_gps_required = $this->fotorama_elevation_options['images_with_gps_required_5']; // Images with GPS required
		$ignore_custom_sort = $this->fotorama_elevation_options['ignore_custom_sort_6']; // Ignore custom sort
		$show_address_of_start = $this->fotorama_elevation_options['show_address_of_start_7']; // Show address of start
		$text_for_start_address = $this->fotorama_elevation_options['text_for_start_address_8']; // Text for Start address
		$general_text_for_the_fotorama_alt = $this->fotorama_elevation_options['general_text_for_the_fotorama_alt_9']; // General text for the Fotorama alt
		$height_of_map = $this->fotorama_elevation_options['height_of_map_10']; // Height of Map
		$height_of_chart = $this->fotorama_elevation_options['height_of_chart_11']; // Height of Chart
		$max_width_of_container = $this->fotorama_elevation_options['max_width_of_container_12']; // Max Width of Container
		?>

		<div class="wrap">
			<h2>Settings for Fotorama-Elevation Plugin</h2>
			<h4>General Settings for the Fotorama Elevation Plugin that are used for every page or post where the Plugin is used. All settings can be overwritten by parameters of the shortcode.</h4>
			<?php settings_errors(); ?>
			
			<form method="post" action="options.php" enctype="multipart/form-data">
            <?php
               settings_fields("gpx_section");
               do_settings_sections("gpx_file");
			   submit_button('Save GPX-File');
            ?>
         	</form>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'fotorama_elevation_option_group' );
					do_settings_sections( 'fotorama-elevation-admin' );
					submit_button();
				?>
			</form>
		
            <h3>List of shortcode Parameters:</h3>
			<p><b>Complete shortcode with the above settings: </br></b> <?php
				$example = '[fotomulti imgpath="' . $path_to_images_for_fotorama .'" ';
				$example.= 'gpxpath="' . $path_to_gpx_files . '" ';
				$example.= 'gpxfile="test.gpx" ';
				$example.= 'mapheight="' . $height_of_map . '" ';
				$example.= 'chartheight="' . $height_of_chart . '" ';
				$example.= 'dload="' . $download_gpx_files . '" ';
				$example.= 'alttext="' . $general_text_for_the_fotorama_alt . '" ';
				$example.= 'ignoresort="' . $ignore_custom_sort . '" ';
				$example.= 'showadress="' . $show_address_of_start . '" ';
				$example.= 'adresstext="' . $text_for_start_address . '" ';
				$example.= 'requiregps="' . $images_with_gps_required . '" ';
				$example.= 'maxwidth="' . $max_width_of_container . '" ';
				$example.= 'showcaption="' . $show_caption . '" ';
				$example.= 'eletheme="' . $colour_theme_for_leaflet_elevation . '"] ';
		
			 	echo $example;
			?></p>

			<style type="text/css">
				.tg  {border-collapse:collapse;border-spacing:2;background-color: white;}
				.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
				overflow:hidden;padding:10px 5px;word-break:normal;}
				.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
				font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
				.tg .tg-dncm{border-color:inherit;font-weight:bold;position:-webkit-sticky;position:sticky;text-align:left;top:-1px;
				vertical-align:top;will-change:transform;background-color: goldenrod;}
				.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
				.tg tr:nth-child(even) {background-color:lightgray;}
		
			</style>

			<table class="tg">
			<thead>
			<tr>
				<th class="tg-dncm">Shortcode</th>
				<th class="tg-dncm">Value (Default first)</th>
				<th class="tg-dncm">Example</th>
				<th class="tg-dncm">Description</th>
			</tr>
			</thead>
			<tbody>
			<tr>
				<td class="tg-0pky">gpxpath</td>
				<td class="tg-0pky">gpx</td>
				<td class="tg-0pky">gpxpath="gpx"</td>
				<td class="tg-0pky">Path to file with GPX-Track(s) relative to the Wordpress uploads folder, e.g: ../wordpress/wp-content/uploads/gpx</td>
			</tr>
			<tr>
				<td class="tg-0pky">gpxfile</td>
				<td class="tg-0pky">'' / test.gpx</td>
				<td class="tg-0pky">gpxfile="test.gpx"</td>
				<td class="tg-0pky">File with gpx-track, e.g: ../wordpress/wp-content/uploads/gpx/test.gpx</td>
			</tr>
			<tr>
				<td class="tg-0pky">mapheight</td>
				<td class="tg-0pky">450</td>
				<td class="tg-0pky">mapheight="450"</td>
				<td class="tg-0pky">Height of the leaflet map in pixels (px)</td>
			</tr>
			<tr>
				<td class="tg-0pky">chartheight</td>
				<td class="tg-0pky">200</td>
				<td class="tg-0pky">chartheight="200"</td>
				<td class="tg-0pky">Height of the leaflet elevation chart in pixels (px)</td>
			</tr>
			<tr>
				<td class="tg-0pky">imgpath</td>
				<td class="tg-0pky">Bilder</td>
				<td class="tg-0pky">imgpath="Bilder"</td>
				<td class="tg-0pky">Path the images relative to the Wordpress uploads folder, e.g: ../wordpress/wp-content/uploads/galleries/holiday2020</td>
			</tr>
			<tr>
				<td class="tg-0pky">dload</td>
				<td class="tg-0pky">yes / no</td>
				<td class="tg-0pky">dload="yes"</td>
				<td class="tg-0pky">Provide download link for the GPX-Tracks, if "yes".</td>
			</tr>
			<tr>
				<td class="tg-0pky">alttext</td>
				<td class="tg-0pky">''</td>
				<td class="tg-0pky">alttext="Image Slider with map from holiday"</td>
				<td class="tg-0pky">Alltext for the fotorama slider for SEO</td>
			</tr>
			<tr>
				<td class="tg-0pky">ignoresort</td>
				<td class="tg-0pky">false / true</td>
				<td class="tg-0pky">ignoresort="false"</td>
				<td class="tg-0pky">Ignore custom sort even if provided by Wordpress. If checked sort by date ascending</td>
			</tr>
			<tr>
				<td class="tg-0pky">showadress</td>
				<td class="tg-0pky">true / false</td>
				<td class="tg-0pky">showadress="true"</td>
				<td class="tg-0pky">Show start adress of the tour. GPX-coords are taken from the first point in the GPX-track or from the first image</td>
			</tr>
			<tr>
				<td class="tg-0pky">adresstext</td>
				<td class="tg-0pky">Startadresse</td>
				<td class="tg-0pky">adresstext="Startadresse"</td>
				<td class="tg-0pky">Text for header above start address</td>
			</tr>
			<tr>
				<td class="tg-0pky">requiregps</td>
				<td class="tg-0pky">true / false</td>
				<td class="tg-0pky">requiregps="true"</td>
				<td class="tg-0pky">Require images to have GPS-data in EXIF. Show image only if it provides GPS-Data in its EXIF.</td>
			</tr>
			<tr>
				<td class="tg-0pky">maxwidth</td>
				<td class="tg-0pky">600</td>
				<td class="tg-0pky">maxwidth="600"</td>
				<td class="tg-0pky">Maximum width of the whole container with slider and map</td>
			</tr>
			<tr>
				<td class="tg-0pky">showcaption</td>
				<td class="tg-0pky">true / false</td>
				<td class="tg-0pky">showcaption="true"</td>
				<td class="tg-0pky">Show the caption in the fotorama slider</td>
			</tr>
			<tr>
				<td class="tg-0pky">eletheme</td>
				<td class="tg-0pky">lime-theme</td>
				<td class="tg-0pky">eletheme="lime-theme"</td>
				<td class="tg-0pky">Theme for leaflet elevation. Other themes are: steelblue-theme, purple-theme, yellow-theme, red-theme, magenta-theme, lightblue-theme and martin-theme. Martin-theme is my special theme.</td>
			</tr>
			</tbody>

			</table>

		</div>
		<?php 
	}

	public function fotorama_elevation_page_init() { // == demo_settings_page()
		register_setting(
			'fotorama_elevation_option_group', // option_group
			'fotorama_elevation_option_name', // option_name
			array( $this, 'fotorama_elevation_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'fotorama_elevation_setting_section', // id
			'Fotorama Settings', // title
			array( $this, 'fotorama_elevation_section_info' ), // callback
			'fotorama-elevation-admin' // page
		);

		add_settings_field(
			'path_to_images_for_fotorama_0', // id
			'Path to Images for Fotorama', // title
			array( $this, 'path_to_images_for_fotorama_0_callback' ), // callback
			'fotorama-elevation-admin', // page
			'fotorama_elevation_setting_section' // section
        );
        
        add_settings_field(
			'show_caption_4', // id
			'Show Caption', // title
			array( $this, 'show_caption_4_callback' ), // callback
			'fotorama-elevation-admin', // page
			'fotorama_elevation_setting_section' // section
        );
        
        add_settings_field(
			'images_with_gps_required_5', // id
			'Images with GPS required', // title
			array( $this, 'images_with_gps_required_5_callback' ), // callback
			'fotorama-elevation-admin', // page
			'fotorama_elevation_setting_section' // section
		);

		add_settings_field(
			'ignore_custom_sort_6', // id
			'Ignore custom sort', // title
			array( $this, 'ignore_custom_sort_6_callback' ), // callback
			'fotorama-elevation-admin', // page
			'fotorama_elevation_setting_section' // section
        );

        add_settings_field(
			'general_text_for_the_fotorama_alt_9', // id
			'General text for the Fotorama alt', // title
			array( $this, 'general_text_for_the_fotorama_alt_9_callback' ), // callback
			'fotorama-elevation-admin', // page
			'fotorama_elevation_setting_section' // section
		);
        
        add_settings_section(
			'leaflet_elevation_setting_section', // id
			'Leaflet Elevation Settings', // title
			array( $this, 'leaflet_elevation_section_info' ), // callback
			'fotorama-elevation-admin' // page
		);

		add_settings_field(
			'colour_theme_for_leaflet_elevation_1', // id
			'Colour Theme for Leaflet Elevation', // title
			array( $this, 'colour_theme_for_leaflet_elevation_1_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'path_to_gpx_files_2', // id
			'Path to GPX-Files', // title
			array( $this, 'path_to_gpx_files_2_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'download_gpx_files_3', // id
			'Download GPX-Files', // title
			array( $this, 'download_gpx_files_3_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'show_address_of_start_7', // id
			'Show address of start', // title
			array( $this, 'show_address_of_start_7_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'text_for_start_address_8', // id
			'Text for Start address', // title
			array( $this, 'text_for_start_address_8_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'height_of_map_10', // id
			'Height of Map in px', // title
			array( $this, 'height_of_map_10_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'height_of_chart_11', // id
			'Height of Chart in px', // title
			array( $this, 'height_of_chart_11_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);

		add_settings_field(
			'max_width_of_container_12', // id
			'Max Width of Container in px', // title
			array( $this, 'max_width_of_container_12_callback' ), // callback
			'fotorama-elevation-admin', // page
			'leaflet_elevation_setting_section' // section
		);
	
		add_settings_section("gpx_section", "GPX-File Upload", null, "gpx_file");
    	add_settings_field("gpx-file", "GPX-File", array( $this, "gpx_file_display"), "gpx_file", "gpx_section");  
		register_setting("gpx_section", "gpx-file", array( $this, "handle_file_upload") );
		
	}

	public function gpx_file_display() {
	
		?><input type="file" name="gpx-file" /><?php // create html button for file name
		echo ('Upload "' .  get_option('gpx-file') . '"');
	}

	public function handle_file_upload($option) { // wird nur einmal aufgerufen

		if ( ! function_exists( 'wp_handle_upload' ) ) {
			require_once( ABSPATH . 'wp-admin/includes/file.php' );
		}

		$this->fotorama_elevation_options = get_option( 'fotorama_elevation_option_name' );
		$this->up_dir = wp_get_upload_dir()['basedir'];     // upload_dir
		$file = $this->my_sanitize_text($option);

		$path = $this->up_dir . '/' . $this->fotorama_elevation_options['path_to_gpx_files_2'];
		$complete = $path . '/' . $file;
		$success = false;

		if( is_dir($path) ) {
			//echo "The Directory {$path} exists";
		} else {
			mkdir($path , 0777);
			//echo "The Directory {$path} was created";
			$success = true;
		}

		if(! is_file($complete)) {
			$name_file = $_FILES['gpx-file']['name'];
			$tmp_name = $_FILES['gpx-file']['tmp_name']; 
			$result = move_uploaded_file( $tmp_name, $path. '/'.$name_file );
			if( $result )  {
				$temp = 'of '. $name_file . '" successful!';
			} else {
				$temp = "The file was not uploaded";
			}

			//$urls = wp_handle_upload($complete, array('test_form' => FALSE));
			//$temp = $urls["url"]; // setzt den String für get_option('gpx-file') : Ausgabe kann damit gesteuert werden!
			//if ($temp == null) {
			//  $temp =  'No Success!';
			//} 
			return $temp;  
		}
		
		return $option;
	}

	public function fotorama_elevation_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['path_to_images_for_fotorama_0'] ) ) {
			$sanitary_values['path_to_images_for_fotorama_0'] = $this->my_sanitize_path( $input['path_to_images_for_fotorama_0'] );
		}

		if ( isset( $input['colour_theme_for_leaflet_elevation_1'] ) ) {
			$sanitary_values['colour_theme_for_leaflet_elevation_1'] = $input['colour_theme_for_leaflet_elevation_1'];
		}

		if ( isset( $input['path_to_gpx_files_2'] ) ) {
			$sanitary_values['path_to_gpx_files_2'] = $this->my_sanitize_path( $input['path_to_gpx_files_2'] );
		}

		if ( isset( $input['download_gpx_files_3'] ) ) { // wird nur durchlaufen, wenn button gecheckt ist, sonst nicht.
			$sanitary_values['download_gpx_files_3'] = 'true';
		} else {
			$sanitary_values['download_gpx_files_3'] = 'false';
		}

		if ( isset( $input['show_caption_4'] ) ) {
			//$sanitary_values['show_caption_4'] = $input['show_caption_4'];
			$sanitary_values['show_caption_4'] = 'true';
		} else {
			$sanitary_values['show_caption_4'] = 'false';
		}

		if ( isset( $input['images_with_gps_required_5'] ) ) {
			$sanitary_values['images_with_gps_required_5'] = 'true';
		} else {
			$sanitary_values['images_with_gps_required_5'] = 'false';
		}

		if ( isset( $input['ignore_custom_sort_6'] ) ) {
			$sanitary_values['ignore_custom_sort_6'] = 'true';
		} else {
			$sanitary_values['ignore_custom_sort_6'] = 'false';
		}

		if ( isset( $input['show_address_of_start_7'] ) ) {
			$sanitary_values['show_address_of_start_7'] = 'true';
		} else {
			$sanitary_values['show_address_of_start_7'] = 'false';
		}

		if ( isset( $input['text_for_start_address_8'] ) ) {
			$sanitary_values['text_for_start_address_8'] = $this->my_sanitize_text( $input['text_for_start_address_8'] );
		}

		if ( isset( $input['general_text_for_the_fotorama_alt_9'] ) ) {
			$sanitary_values['general_text_for_the_fotorama_alt_9'] = $this->my_sanitize_text( $input['general_text_for_the_fotorama_alt_9'] );
		}

		if ( isset( $input['height_of_map_10'] ) ) {
			$sanitary_values['height_of_map_10'] = $this->my_sanitize_int_with_limits($input['height_of_map_10'], $this->min_height_map, $this->max_height_map );
		}

		if ( isset( $input['height_of_chart_11'] ) ) {
			$sanitary_values['height_of_chart_11'] = $this->my_sanitize_int_with_limits($input['height_of_chart_11'], $this->min_height_chart, $this->max_height_chart );
		}

		if ( isset( $input['max_width_of_container_12'] ) ) {
			$sanitary_values['max_width_of_container_12'] = $this->my_sanitize_int_with_limits($input['max_width_of_container_12'], $this->min_width, $this->max_width );
		}

		if ( isset( $input['gpx_file'] ) ) {
			$sanitary_values['gpx_file'] = sanitize_text_field( $input['gpx_file'] );
		} else { $sanitary_values['gpx_file'] = '';}

		return $sanitary_values;
	}

	public function fotorama_elevation_section_info() {	
    }
    
    public function leaflet_elevation_section_info() {
	}

	public function path_to_images_for_fotorama_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[path_to_images_for_fotorama_0]" id="path_to_images_for_fotorama_0" value="%s"><p>%s</p>',
			isset( $this->fotorama_elevation_options['path_to_images_for_fotorama_0'] ) ? esc_attr( $this->fotorama_elevation_options['path_to_images_for_fotorama_0']) : '',
			$this->up_dir . '/' . $this->fotorama_elevation_options['path_to_images_for_fotorama_0']
		);
	}

	public function colour_theme_for_leaflet_elevation_1_callback() {
		?> <select name="fotorama_elevation_option_name[colour_theme_for_leaflet_elevation_1]" id="colour_theme_for_leaflet_elevation_1">
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'martin-theme') ? 'selected' : '' ; ?>
			<option value="martin-theme" <?php echo $selected; ?>>Martin</option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'lime-theme') ? 'selected' : '' ; ?>
			<option value="lime-theme" <?php echo $selected; ?>>Lime</option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'steelblue-theme') ? 'selected' : '' ; ?>
			<option value="steelblue-theme" <?php echo $selected; ?>>Steelblue </option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'purple-theme') ? 'selected' : '' ; ?>
			<option value="purple-theme" <?php echo $selected; ?>>Purple</option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'yellow-theme') ? 'selected' : '' ; ?>
			<option value="yellow-theme" <?php echo $selected; ?>>Yellow</option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'red-theme') ? 'selected' : '' ; ?>
			<option value="red-theme" <?php echo $selected; ?>>Red</option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'magenta-theme') ? 'selected' : '' ; ?>
			<option value="magenta-theme" <?php echo $selected; ?>>Magenta </option>
			<?php $selected = (isset( $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] ) && $this->fotorama_elevation_options['colour_theme_for_leaflet_elevation_1'] === 'lightblue-theme') ? 'selected' : '' ; ?>
			<option value="lightblue-theme" <?php echo $selected; ?>>Lightblue</option>
		</select> <?php
	}

	public function path_to_gpx_files_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[path_to_gpx_files_2]" id="path_to_gpx_files_2" value="%s"><p>%s</p>',
			isset( $this->fotorama_elevation_options['path_to_gpx_files_2'] ) ? esc_attr( $this->fotorama_elevation_options['path_to_gpx_files_2']) : '', 
			$this->up_dir . '/' . $this->fotorama_elevation_options['path_to_gpx_files_2']
		);
	}

	public function download_gpx_files_3_callback() {
		$param = 1;
		printf(
			'<input type="checkbox" name="fotorama_elevation_option_name[download_gpx_files_3]" id="download_gpx_files_3" value="download_gpx_files_3" %s> <label for="download_gpx_files_3">Provide download link for GPX-Files</label>',
			( isset( $this->fotorama_elevation_options['download_gpx_files_3'] ) && $this->fotorama_elevation_options['download_gpx_files_3'] === 'true' ) ? 'checked' : '' 
		);
	}

	public function show_caption_4_callback() {
		printf(
			'<input type="checkbox" name="fotorama_elevation_option_name[show_caption_4]" id="show_caption_4" value="show_caption_4" %s> <label for="show_caption_4">Show the Caption in Fotorama</label>',
			( isset( $this->fotorama_elevation_options['show_caption_4'] ) && $this->fotorama_elevation_options['show_caption_4'] === 'true' ) ? 'checked' : ''
		);
	}

	public function images_with_gps_required_5_callback() {
		printf(
			'<input type="checkbox" name="fotorama_elevation_option_name[images_with_gps_required_5]" id="images_with_gps_required_5" value="images_with_gps_required_5" %s> <label for="images_with_gps_required_5">Show images only if they provide GPS-Data in EXIF</label>',
			( isset( $this->fotorama_elevation_options['images_with_gps_required_5'] ) && $this->fotorama_elevation_options['images_with_gps_required_5'] === 'true' ) ? 'checked' : ''
		);
	}

	public function ignore_custom_sort_6_callback() {
		printf(
			'<input type="checkbox" name="fotorama_elevation_option_name[ignore_custom_sort_6]" id="ignore_custom_sort_6" value="ignore_custom_sort_6" %s> <label for="ignore_custom_sort_6">Ignore custom sort even if provided by Wordpress. Sort ascending by date taken if checked.</label>',
			( isset( $this->fotorama_elevation_options['ignore_custom_sort_6'] ) && $this->fotorama_elevation_options['ignore_custom_sort_6'] === 'true' ) ? 'checked' : ''
		);
	}

	public function show_address_of_start_7_callback() {
		printf(
			'<input type="checkbox" name="fotorama_elevation_option_name[show_address_of_start_7]" id="show_address_of_start_7" value="show_address_of_start_7" %s> <label for="show_address_of_start_7">Show the address of the starting point (taken from the first image or GPX-coordinate in the GPX-track)</label>',
			( isset( $this->fotorama_elevation_options['show_address_of_start_7'] ) && $this->fotorama_elevation_options['show_address_of_start_7'] === 'true' ) ? 'checked' : ''
		);
	}

	public function text_for_start_address_8_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[text_for_start_address_8]" id="text_for_start_address_8" value="%s">',
			isset( $this->fotorama_elevation_options['text_for_start_address_8'] ) ? esc_attr( $this->fotorama_elevation_options['text_for_start_address_8']) : ''
		);
	}

	public function general_text_for_the_fotorama_alt_9_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[general_text_for_the_fotorama_alt_9]" id="general_text_for_the_fotorama_alt_9" value="%s">',
			isset( $this->fotorama_elevation_options['general_text_for_the_fotorama_alt_9'] ) ? esc_attr( $this->fotorama_elevation_options['general_text_for_the_fotorama_alt_9']) : ''
		);
	}

	public function height_of_map_10_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[height_of_map_10]" id="height_of_map_10" value="%s"><p>Min: %s px, Max: %s px</p>',
			isset( $this->fotorama_elevation_options['height_of_map_10'] ) ? esc_attr( $this->fotorama_elevation_options['height_of_map_10']) : '',
			$this->min_height_map, $this->max_height_map
		);
	}

	public function height_of_chart_11_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[height_of_chart_11]" id="height_of_chart_11" value="%s"><p>Min: %s px, Max: %s px</p>',
			isset( $this->fotorama_elevation_options['height_of_chart_11'] ) ? esc_attr( $this->fotorama_elevation_options['height_of_chart_11']) : '',
			$this->min_height_chart, $this->max_height_chart
		);
	}

	public function max_width_of_container_12_callback() {
		printf(
			'<input class="regular-text" type="text" name="fotorama_elevation_option_name[max_width_of_container_12]" id="max_width_of_container_12" value="%s"><p>Min: %s px, Max: %s px</p>',
			isset( $this->fotorama_elevation_options['max_width_of_container_12'] ) ? esc_attr( $this->fotorama_elevation_options['max_width_of_container_12']) : '',
			$this->min_width, $this->max_width
		);
	}

	private function my_sanitize_path ($inp) {
		$inp = sanitize_text_field( $inp);
		$inp = filter_var($inp, FILTER_SANITIZE_STRING);
		$inp = preg_replace("/[^A-Za-z0-9-_\/]/", "", $inp);
		$inp = rtrim($inp,'/');
		$inp = rtrim($inp,'\\');
		$inp = ltrim($inp,'/');
		$inp = ltrim($inp,'\\');
		return $inp;
	}

	private function my_sanitize_text ($inp) {
		$inp = sanitize_text_field( $inp);
		$inp = filter_var($inp, FILTER_SANITIZE_STRING);
		return $inp;
	}

	private function my_sanitize_int_with_limits($inp, $min, $max) {
		$inp = preg_replace("/[^0-9]/", "", $inp);
		$val = intval( $inp);
		if (filter_var($val, FILTER_VALIDATE_INT, array("options" => array("min_range"=>$min, "max_range"=>$max))) === false) {
			// echo("Variable value is not within the legal range");
			($val < $min) ? $val = $min : $val = $max;
		} else {
			//echo("Variable value is within the legal range");
		}
		return strval($val);
	}

}


/* 
 * Retrieve this value with:
 * $fotorama_elevation_options = get_option( 'fotorama_elevation_option_name' ); // Array of All Options
 * $path_to_images_for_fotorama_0 = $fotorama_elevation_options['path_to_images_for_fotorama_0']; // Path to Images for Fotorama
 * $colour_theme_for_leaflet_elevation_1 = $fotorama_elevation_options['colour_theme_for_leaflet_elevation_1']; // Colour Theme for Leaflet Elevation
 * $path_to_gpx_files_2 = $fotorama_elevation_options['path_to_gpx_files_2']; // Path to GPX-Files
 * $download_gpx_files_3 = $fotorama_elevation_options['download_gpx_files_3']; // Download GPX-Files
 * $show_caption_4 = $fotorama_elevation_options['show_caption_4']; // Show Caption
 * $images_with_gps_required_5 = $fotorama_elevation_options['images_with_gps_required_5']; // Images with GPS required
 * $ignore_custom_sort_6 = $fotorama_elevation_options['ignore_custom_sort_6']; // Ignore custom sort
 * $show_address_of_start_7 = $fotorama_elevation_options['show_address_of_start_7']; // Show address of start
 * $text_for_start_address_8 = $fotorama_elevation_options['text_for_start_address_8']; // Text for Start address
 * $general_text_for_the_fotorama_alt_9 = $fotorama_elevation_options['general_text_for_the_fotorama_alt_9']; // General text for the Fotorama alt
 * $height_of_map_10 = $fotorama_elevation_options['height_of_map_10']; // Height of Map
 * $height_of_chart_11 = $fotorama_elevation_options['height_of_chart_11']; // Height of Chart
 * $max_width_of_container_12 = $fotorama_elevation_options['max_width_of_container_12']; // Max Width of Container
 */
